name: Delete doc comment trigger

on:
  pull_request:
    types: [ closed ]


jobs:
  delete:
    uses: huggingface/doc-builder/.github/workflows/delete_doc_comment_trigger.yml@61704e23fa97c0502ce5355c489c6bec4194bff1  # main
    with:
      pr_number: ${{ github.event.number }}