name: Delete doc comment trigger

on:
  pull_request:
    types: [ closed ]


jobs:
  delete:
    uses: huggingface/doc-builder/.github/workflows/delete_doc_comment_trigger.yml@c69e96c087165ba49b1788e0c3464654dd60253c  # main
    with:
      pr_number: ${{ github.event.number }}